name: Build on Develop

on:
  push:
    branches:
      - Develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Use your preferred Python version

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Build application
      run: |
        # Add your build commands here
        echo "Building the application..."

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: |
          # Specify the build artifact paths here
          build/
