name: Build and Test on Test

on:
  push:
    branches:
      - Test

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Use your preferred Python version

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Build application
      run: |
        # Add your build commands here
        echo "Building the application..."

    - name: Run tests
      run: |
        # Run your tests here
        python -m unittest discover -s tests

    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: |
          # Specify the test result paths here
          tests/reports/
